import type { Product } from "./types";

const ALL = [
  "f150-2015", "civic-2018", "silverado-2019", "camry-2017",
  "explorer-2016", "ram1500-2020", "altima-2019", "crv-2020",
];
const TRUCKS = ["f150-2015", "silverado-2019", "explorer-2016", "ram1500-2020"];
const CARS = ["civic-2018", "camry-2017", "altima-2019", "crv-2020"];

// The commercial fleet, by unit number (see `vehicles` in lib/suppliers.ts).
// Fleet fitment is deliberately narrow: a 235/65R16C van tire and a 19.5 in
// medium-duty tire share a category and nothing else, so most fleet rows name
// one or two units rather than a class.
const TRANSIT = "transit250-2021"; // VAN-17
const SPRINTER = "sprinter2500-2020"; // VAN-22
const F150F = "f150fleet-2022"; // TRUCK-08
const SILVERADO_HD = "silverado2500-2021"; // TRUCK-12
const E450 = "e450-2019"; // BOX-03
const NPR = "npr-2020"; // BOX-07

const FLEET = [TRANSIT, SPRINTER, F150F, SILVERADO_HD, E450, NPR];
const FLEET_VANS = [TRANSIT, SPRINTER];
const FLEET_PICKUPS = [F150F, SILVERADO_HD];
const FLEET_BOX = [E450, NPR];
const FLEET_FORD = [TRANSIT, F150F, E450];

type Row = [
  id: string, name: string, brand: string, partNumber: string,
  category: string, subCategory: string, image: string,
  price: number, listPrice: number, supplierId: string, stock: number,
  rating: number, reviews: number, warranty: string,
  position: string, description: string,
  specs: [string, string][], fits: string[], core?: number
];

const rows: Row[] = [
  // ---------------- Brakes ----------------
  ["bp-001", "QuietCast Premium Disc Brake Rotor", "Bosch", "26010739", "Brakes", "Disc Brake Rotor", "brake-rotor", 62.99, 84.99, "midtown", 24, 4.6, 318, "2 Year Limited", "Front",
    "Precision-balanced coated rotor with an anti-corrosion finish that resists rust bloom and keeps braking smooth and quiet through the life of the pad.",
    [["Outside Diameter", "13.78 in"], ["Thickness", "1.34 in"], ["Bolt Holes", "6"], ["Finish", "Aluminum-zinc coated"], ["Vented", "Yes"]], TRUCKS],
  ["bp-002", "Advanced Coated Disc Brake Rotor", "Raybestos", "980612R", "Brakes", "Disc Brake Rotor", "brake-rotor", 48.5, 69.99, "interstate", 16, 4.4, 187, "1 Year Limited", "Front",
    "Fully coated, non-directional finish rotor machined to OE runout tolerance for vibration-free stops.",
    [["Outside Diameter", "12.99 in"], ["Thickness", "1.10 in"], ["Bolt Holes", "5"], ["Finish", "Coated"], ["Vented", "Yes"]], CARS],
  ["bp-003", "Original Performance Disc Brake Rotor", "ACDelco", "18A2650AC", "Brakes", "Disc Brake Rotor", "brake-rotor", 39.99, 55.0, "summit", 41, 4.2, 96, "1 Year Limited", "Rear",
    "Direct-fit replacement rotor manufactured to original equipment specifications for consistent pedal feel.",
    [["Outside Diameter", "13.58 in"], ["Thickness", "1.02 in"], ["Bolt Holes", "6"], ["Finish", "Bare"], ["Vented", "Yes"]], TRUCKS],
  ["bp-010", "QuietCast Premium Ceramic Brake Pad Set", "Bosch", "BC1414", "Brakes", "Brake Pad Set", "brake-pad", 44.99, 61.99, "northstar", 33, 4.7, 512, "3 Year Limited", "Front",
    "Ceramic friction formula with a synthetic lubricant layer and molded shims for near-silent operation and very low dust.",
    [["Friction", "Ceramic"], ["Shims", "Molded rubber-core"], ["Hardware", "Included"], ["Pieces", "4"]], ALL],
  ["bp-011", "ProGrade Semi-Metallic Brake Pad Set", "Wagner", "MX1414", "Brakes", "Brake Pad Set", "brake-pad", 32.75, 45.0, "midtown", 58, 4.3, 240, "2 Year Limited", "Front",
    "Semi-metallic compound engineered for heavier loads and towing, with strong fade resistance at high temperature.",
    [["Friction", "Semi-metallic"], ["Shims", "Steel"], ["Hardware", "Included"], ["Pieces", "4"]], TRUCKS],
  ["bp-012", "Extra Duty Ceramic Brake Pad Set", "Akebono", "ACT1414", "Brakes", "Brake Pad Set", "brake-pad", 58.4, 78.0, "keystone", 12, 4.8, 431, "Lifetime", "Rear",
    "Ultra-premium ceramic pads that deliver OE-level stopping power with almost no rotor wear.",
    [["Friction", "Ceramic"], ["Shims", "Multi-layer"], ["Hardware", "Included"], ["Pieces", "4"]], ALL],
  ["bp-020", "Remanufactured Brake Caliper", "Cardone", "19-B3345", "Brakes", "Brake Caliper", "brake-caliper", 89.99, 124.0, "apex", 7, 4.1, 88, "1 Year Limited", "Front Left",
    "Fully remanufactured caliper with new seals, boots and hardware, pressure tested before shipping.",
    [["Bore", "1.89 in"], ["Piston", "Phenolic"], ["Bracket", "Included"], ["Core Required", "Yes"]], TRUCKS, 45],
  ["bp-021", "Loaded Brake Caliper with Pads", "Raybestos", "FRC12525N", "Brakes", "Brake Caliper", "brake-caliper", 142.5, 189.0, "gateway", 5, 4.5, 63, "2 Year Limited", "Front Right",
    "New loaded caliper assembly shipped with pads and hardware installed, ready to bolt on.",
    [["Bore", "2.36 in"], ["Piston", "Steel"], ["Pads Included", "Yes"], ["Core Required", "No"]], CARS],

  // ---------------- Filters ----------------
  ["fl-001", "Extra Guard Spin-On Oil Filter", "Fram", "PH3600", "Filters", "Oil Filter", "oil-filter", 8.49, 12.99, "midtown", 240, 4.4, 1904, "10,000 Miles", "",
    "Spin-on oil filter with a heavy-duty steel base plate and silicone anti-drainback valve for fast lubrication at start-up.",
    [["Height", "3.4 in"], ["Thread", "3/4-16"], ["Anti-Drainback", "Silicone"], ["Bypass PSI", "11"]], ALL],
  ["fl-002", "XP Synthetic Media Oil Filter", "Wix", "57060XP", "Filters", "Oil Filter", "oil-filter", 13.25, 18.5, "summit", 132, 4.8, 742, "20,000 Miles", "",
    "Full synthetic media rated for extended drain intervals with a wire-backed element that will not collapse.",
    [["Height", "3.8 in"], ["Thread", "22mm x 1.5"], ["Anti-Drainback", "Silicone"], ["Bypass PSI", "13"]], ALL],
  ["fl-003", "Professional Engine Oil Filter", "ACDelco", "PF63E", "Filters", "Oil Filter", "oil-filter", 10.95, 15.0, "interstate", 88, 4.6, 388, "1 Year Limited", "",
    "OE-specification filter with a high-efficiency cellulose blend media and a durable nitrile gasket.",
    [["Height", "3.2 in"], ["Thread", "M22 x 1.5"], ["Anti-Drainback", "Nitrile"], ["Bypass PSI", "15"]], ALL],
  ["fl-010", "Rigid Panel Engine Air Filter", "K&N", "33-2385", "Filters", "Air Filter", "air-filter", 54.99, 72.0, "northstar", 22, 4.7, 655, "Million Mile", "",
    "Washable, reusable cotton-gauze panel filter that increases airflow while trapping fine dust.",
    [["Type", "Reusable cotton"], ["Length", "12.5 in"], ["Width", "9.4 in"], ["Height", "1.5 in"]], ALL],
  ["fl-011", "Standard Engine Air Filter", "Wix", "49103", "Filters", "Air Filter", "air-filter", 21.4, 29.99, "keystone", 64, 4.5, 214, "1 Year Limited", "",
    "Pleated cellulose panel filter with a molded polyurethane frame that seals tightly to the airbox.",
    [["Type", "Cellulose panel"], ["Length", "11.8 in"], ["Width", "8.7 in"], ["Height", "1.7 in"]], ALL],
  ["fl-020", "FreshBreeze Cabin Air Filter", "Fram", "CF10134", "Filters", "Cabin Air Filter", "cabin-filter", 19.99, 26.5, "midtown", 74, 4.5, 480, "1 Year Limited", "",
    "Activated carbon and baking soda cabin filter that captures pollen, road dust and lingering odors.",
    [["Media", "Carbon + particulate"], ["Length", "9.4 in"], ["Width", "8.3 in"], ["Height", "0.8 in"]], ALL],
  ["fl-021", "Particulate Cabin Air Filter", "Bosch", "6055C", "Filters", "Cabin Air Filter", "cabin-filter", 14.25, 19.99, "apex", 110, 4.3, 176, "1 Year Limited", "",
    "Electrostatically charged multi-layer media that removes airborne particles down to 3 microns.",
    [["Media", "Particulate"], ["Length", "8.9 in"], ["Width", "7.5 in"], ["Height", "0.7 in"]], CARS],

  // ---------------- Engine ----------------
  ["en-001", "Iridium IX Spark Plug", "NGK", "BKR5EIX-11", "Engine", "Spark Plug", "spark-plug", 9.85, 13.5, "summit", 320, 4.8, 2210, "1 Year Limited", "",
    "Fine-wire iridium center electrode with a tapered ground electrode for a stronger, more complete burn.",
    [["Electrode", "Iridium"], ["Gap", "0.044 in"], ["Thread", "14mm"], ["Reach", "0.749 in"], ["Heat Range", "5"]], ALL],
  ["en-002", "Iridium TT Spark Plug", "Denso", "IKH20TT", "Engine", "Spark Plug", "spark-plug", 11.2, 15.75, "interstate", 190, 4.7, 1340, "1 Year Limited", "",
    "Twin-tip design with iridium center and platinum ground electrode for faster ignition and long service life.",
    [["Electrode", "Iridium/Platinum"], ["Gap", "0.043 in"], ["Thread", "12mm"], ["Reach", "0.984 in"], ["Heat Range", "20"]], CARS],
  ["en-003", "Double Platinum Spark Plug", "Bosch", "8104", "Engine", "Spark Plug", "spark-plug", 6.4, 9.25, "midtown", 260, 4.4, 690, "1 Year Limited", "",
    "Platinum pads on both electrodes maintain a consistent gap over a long replacement interval.",
    [["Electrode", "Double platinum"], ["Gap", "0.050 in"], ["Thread", "14mm"], ["Reach", "0.708 in"], ["Heat Range", "4"]], TRUCKS],
  ["en-010", "Direct Ignition Coil", "Denso", "673-8305", "Engine", "Ignition Coil", "ignition-coil", 46.75, 64.0, "northstar", 28, 4.6, 402, "2 Year Limited", "",
    "Coil-on-plug unit with an epoxy-sealed winding that resists heat, vibration and moisture intrusion.",
    [["Primary Resistance", "0.6 Ohm"], ["Secondary Resistance", "6.9k Ohm"], ["Connector", "3-pin"], ["Boot", "Silicone"]], ALL],
  ["en-011", "Ignition Coil", "Delphi", "GN10328", "Engine", "Ignition Coil", "ignition-coil", 34.9, 48.0, "keystone", 44, 4.3, 158, "1 Year Limited", "",
    "OE-validated coil with a laminated iron core for stable spark energy across the rev range.",
    [["Primary Resistance", "0.5 Ohm"], ["Secondary Resistance", "7.4k Ohm"], ["Connector", "2-pin"], ["Boot", "Silicone"]], CARS],
  ["en-020", "PowerGrip Timing Belt", "Gates", "T295", "Engine", "Timing Belt", "timing-belt", 28.6, 39.99, "apex", 19, 4.6, 221, "2 Year Limited", "",
    "HNBR compound belt with high-modulus tensile cords that hold timing under high underhood temperature.",
    [["Teeth", "153"], ["Width", "25.4mm"], ["Profile", "Round tooth"], ["Material", "HNBR"]], CARS],
  ["en-021", "Micro-V Serpentine Belt", "Gates", "K060850", "Engine", "Serpentine Belt", "belt", 24.35, 33.5, "midtown", 96, 4.7, 588, "2 Year Limited", "",
    "EPDM multi-rib belt that resists cracking and keeps tension far longer than conventional rubber.",
    [["Ribs", "6"], ["Length", "85.0 in"], ["Width", "0.83 in"], ["Material", "EPDM"]], ALL],
  ["en-030", "Engine Water Pump", "Gates", "43549", "Engine", "Water Pump", "water-pump", 68.9, 92.0, "summit", 14, 4.5, 176, "2 Year Limited", "",
    "Cast-iron housing water pump with a heavy-duty bearing and a mechanical seal rated for long coolant life.",
    [["Impeller", "Stamped steel"], ["Gasket", "Included"], ["Pulley", "Not included"], ["Inlet", "1.25 in"]], ALL],
  ["en-031", "Engine Coolant Thermostat", "Motorad", "7288-192", "Engine", "Thermostat", "thermostat", 15.75, 22.0, "interstate", 62, 4.4, 132, "1 Year Limited", "",
    "Calibrated wax-pellet thermostat with a stainless frame that opens at a precise temperature every cycle.",
    [["Opening Temp", "192 F"], ["Diameter", "54mm"], ["Housing", "Not included"], ["Gasket", "Included"]], ALL],
  ["en-040", "Fuel Injector", "Bosch", "62685", "Engine", "Fuel Injector", "fuel-injector", 78.5, 104.0, "gateway", 11, 4.5, 94, "1 Year Limited", "",
    "Flow-matched multi-hole injector calibrated to OE spray pattern for a smooth idle and clean combustion.",
    [["Flow Rate", "34 lb/hr"], ["Ohms", "12.0"], ["Connector", "EV6"], ["O-Rings", "Included"]], TRUCKS],
  ["en-050", "Mass Air Flow Sensor", "Denso", "197-6020", "Engine", "Mass Air Flow Sensor", "mass-airflow", 96.4, 128.0, "northstar", 9, 4.6, 141, "2 Year Limited", "",
    "Hot-wire MAF sensor calibrated on OE equipment so fuel trim lands correctly with no relearn drift.",
    [["Type", "Hot wire"], ["Pins", "5"], ["Housing", "Included"], ["Calibrated", "Yes"]], ALL],
  ["en-060", "Oxygen Sensor", "NTK", "24304", "Engine", "Oxygen Sensor", "oxygen-sensor", 62.8, 85.0, "keystone", 26, 4.7, 336, "2 Year Limited", "Upstream",
    "OE-manufacturer heated oxygen sensor with the correct connector and lead length, no splicing required.",
    [["Position", "Upstream"], ["Wires", "4"], ["Lead Length", "18 in"], ["Thread", "M18 x 1.5"]], ALL],

  // ---------------- Electrical ----------------
  ["el-001", "Remanufactured Alternator", "Cardone", "20-8767", "Electrical", "Alternator", "alternator", 168.0, 219.0, "apex", 6, 4.2, 118, "1 Year Limited", "",
    "Remanufactured to OE output with new bearings, brushes and a fully tested rectifier and regulator.",
    [["Amperage", "150A"], ["Voltage", "12V"], ["Pulley", "Clutch, 6-groove"], ["Core Required", "Yes"]], TRUCKS, 60],
  ["el-002", "New Alternator", "Denso", "210-0561", "Electrical", "Alternator", "alternator", 246.5, 315.0, "summit", 4, 4.8, 209, "3 Year Limited", "",
    "Brand-new unit built on the original production line, no core charge and no remanufactured components.",
    [["Amperage", "130A"], ["Voltage", "12V"], ["Pulley", "6-groove"], ["Core Required", "No"]], CARS],
  ["el-010", "Remanufactured Starter Motor", "Bosch", "SR7562X", "Electrical", "Starter Motor", "starter", 132.75, 178.0, "midtown", 8, 4.4, 163, "2 Year Limited", "",
    "Rebuilt starter with a new solenoid, drive assembly and brushes, bench tested for cranking speed and draw.",
    [["Teeth", "11"], ["Rotation", "Clockwise"], ["kW", "1.4"], ["Core Required", "Yes"]], ALL, 40],
  ["el-020", "AGM Automotive Battery, Group 65", "Odyssey", "65-PC1750T", "Electrical", "Battery", "battery", 289.99, 349.0, "gateway", 10, 4.7, 512, "4 Year Free Replacement", "",
    "Absorbed glass mat battery with pure lead plates, high cranking amps and deep-cycle tolerance.",
    [["Group Size", "65"], ["CCA", "950"], ["Reserve Capacity", "145 min"], ["Type", "AGM"], ["Terminal", "Top post"]], TRUCKS],
  ["el-021", "Flooded Automotive Battery, Group 35", "ACDelco", "35AGMPG", "Electrical", "Battery", "battery", 164.5, 199.0, "interstate", 18, 4.3, 287, "3 Year Free Replacement", "",
    "Maintenance-free flooded battery with calcium-alloy grids for strong cold cranking and low self-discharge.",
    [["Group Size", "35"], ["CCA", "650"], ["Reserve Capacity", "100 min"], ["Type", "Flooded"], ["Terminal", "Top post"]], CARS],

  // ---------------- Suspension & Steering ----------------
  ["su-001", "OESpectrum Shock Absorber", "Monroe", "5602", "Suspension & Steering", "Shock Absorber", "shock", 71.25, 95.0, "northstar", 20, 4.6, 372, "Limited Lifetime", "Rear",
    "Twin-tube gas shock with a fluon-banded piston that keeps damping consistent as the fluid heats up.",
    [["Type", "Twin-tube gas"], ["Extended Length", "24.6 in"], ["Compressed Length", "14.8 in"], ["Mount", "Eye/Eye"]], TRUCKS],
  ["su-002", "Quick-Strut Complete Assembly", "Monroe", "171376", "Suspension & Steering", "Strut Assembly", "shock", 186.9, 245.0, "keystone", 6, 4.5, 198, "Limited Lifetime", "Front Left",
    "Fully assembled strut with a new spring, mount and bearing plate, so no spring compressor is needed.",
    [["Type", "Complete assembly"], ["Spring", "Included"], ["Mount", "Included"], ["Side", "Front left"]], CARS],
  ["su-010", "Problem Solver Control Arm and Ball Joint", "Moog", "RK620402", "Suspension & Steering", "Control Arm", "control-arm", 118.4, 158.0, "apex", 12, 4.7, 244, "Limited Lifetime", "Front Lower Left",
    "Stamped-steel arm with a greaseable powdered-metal ball joint that resists the wear that causes clunks.",
    [["Position", "Front lower left"], ["Ball Joint", "Included, greaseable"], ["Bushings", "Pressed in"], ["Material", "Stamped steel"]], TRUCKS],
  ["su-020", "Problem Solver Outer Tie Rod End", "Moog", "ES800465", "Suspension & Steering", "Tie Rod End", "tie-rod", 34.6, 47.5, "midtown", 40, 4.8, 610, "Limited Lifetime", "Front Outer",
    "Hardened stud with a dispersion-hardened bearing and a grease fitting for scheduled maintenance.",
    [["Position", "Front outer"], ["Greaseable", "Yes"], ["Thread", "M14 x 1.5"], ["Stud Taper", "Standard"]], ALL],
  ["su-030", "Wheel Bearing and Hub Assembly", "Timken", "HA590360", "Suspension & Steering", "Wheel Hub Assembly", "wheel-bearing", 124.99, 165.0, "summit", 15, 4.7, 428, "3 Year Limited", "Front",
    "Sealed hub assembly with an integrated ABS tone ring and pre-set bearing preload, bolt-on installation.",
    [["Bolt Pattern", "6 x 135mm"], ["ABS Sensor", "Integrated"], ["Studs", "Included"], ["Position", "Front"]], TRUCKS],

  // ---------------- Cooling ----------------
  ["co-001", "Complete Radiator Assembly", "Spectra Premium", "CU13398", "Cooling", "Radiator", "radiator", 178.5, 235.0, "gateway", 7, 4.4, 129, "2 Year Limited", "",
    "Aluminum-core radiator with crimped plastic tanks, pressure tested and shipped with new mounting hardware.",
    [["Core Rows", "1"], ["Core Height", "17.3 in"], ["Core Width", "27.9 in"], ["Inlet", "1.5 in"], ["Trans Cooler", "Yes"]], TRUCKS],
  ["co-010", "Engine Cooling Fan Assembly", "Dorman", "620-158", "Cooling", "Radiator Fan", "radiator-fan", 142.0, 189.0, "pacific", 5, 4.2, 76, "1 Year Limited", "",
    "Complete fan, motor and shroud assembly matched to OE airflow so the engine holds temperature in traffic.",
    [["Blades", "7"], ["Motor", "Included"], ["Shroud", "Included"], ["Connector", "2-pin"]], CARS],

  // ---------------- Exhaust ----------------
  ["ex-001", "Direct-Fit Catalytic Converter", "Walker", "16456", "Exhaust", "Catalytic Converter", "cat-converter", 312.0, 415.0, "apex", 3, 4.3, 87, "5 Year / 50,000 Mile", "",
    "EPA-compliant direct-fit converter with flanges and hardware in the correct locations for a weld-free install.",
    [["Standard", "EPA compliant"], ["Inlet", "2.25 in"], ["Outlet", "2.25 in"], ["Body Length", "12 in"], ["Fit", "Direct"]], TRUCKS],
  ["ex-010", "Quiet-Flow Stainless Steel Muffler", "Walker", "21619", "Exhaust", "Muffler", "muffler", 88.4, 118.0, "keystone", 14, 4.5, 163, "3 Year Limited", "",
    "Fully welded stainless muffler with a tri-flow chamber that cuts drone without losing exhaust flow.",
    [["Body", "Stainless steel"], ["Inlet", "2.5 in"], ["Outlet", "2.5 in"], ["Overall Length", "26 in"], ["Shape", "Oval"]], ALL],

  // ---------------- Drivetrain ----------------
  ["dr-001", "CV Axle Shaft Assembly", "GSP", "NCV51001", "Drivetrain", "CV Axle", "cv-axle", 96.75, 132.0, "northstar", 13, 4.4, 205, "Limited Lifetime", "Front Left",
    "New complete axle with both joints, boots and grease installed, dynamically balanced to eliminate vibration.",
    [["Position", "Front left"], ["Boots", "Neoprene"], ["ABS Ring", "Included"], ["Core Required", "No"]], CARS],
  ["dr-010", "Clutch Kit with Disc, Pressure Plate and Bearing", "LuK", "07-153", "Drivetrain", "Clutch Kit", "clutch", 268.9, 349.0, "summit", 4, 4.7, 154, "2 Year Limited", "",
    "Complete OE-quality kit with a new disc, pressure plate, release bearing and alignment tool.",
    [["Disc Diameter", "9.45 in"], ["Splines", "22"], ["Bearing", "Included"], ["Alignment Tool", "Included"]], CARS],

  // ---------------- Wheels & Tires ----------------
  ["wt-001", "17 in Alloy Replacement Wheel", "Dorman", "939-104", "Wheels & Tires", "Wheel", "wheel", 168.0, 219.0, "pacific", 8, 4.1, 62, "1 Year Limited", "",
    "OE-style silver-painted alloy wheel, hub-centric and load rated to match the factory wheel it replaces.",
    [["Diameter", "17 in"], ["Width", "7.5 in"], ["Bolt Pattern", "6 x 135mm"], ["Offset", "44mm"], ["Finish", "Silver"]], TRUCKS],
  ["wt-010", "All-Season Touring Tire 245/70R17", "Cooper", "90000032676", "Wheels & Tires", "Tire", "tire", 179.99, 219.99, "gateway", 32, 4.6, 890, "65,000 Mile Treadwear", "",
    "All-season light truck tire with a silica tread compound for wet grip and a quiet, even-wearing pattern.",
    [["Size", "245/70R17"], ["Load Index", "110"], ["Speed Rating", "T"], ["Treadwear", "65,000 mi"], ["Season", "All-season"]], TRUCKS],
  ["wt-011", "All-Season Touring Tire 215/55R17", "Michelin", "04381", "Wheels & Tires", "Tire", "tire", 194.5, 232.0, "interstate", 24, 4.8, 1420, "60,000 Mile Treadwear", "",
    "Premium touring tire with low rolling resistance and confident braking on wet pavement.",
    [["Size", "215/55R17"], ["Load Index", "94"], ["Speed Rating", "V"], ["Treadwear", "60,000 mi"], ["Season", "All-season"]], CARS],

  // ---------------- Fluids ----------------
  ["fd-001", "Full Synthetic Motor Oil 5W-30, 5 Quart", "Mobil 1", "120764", "Fluids", "Motor Oil", "engine-oil", 32.99, 41.99, "midtown", 180, 4.9, 3240, "N/A", "",
    "Full synthetic oil that protects against wear and deposits and stays stable through extended drain intervals.",
    [["Viscosity", "5W-30"], ["Volume", "5 qt"], ["Type", "Full synthetic"], ["Spec", "API SP / ILSAC GF-6A"]], ALL],
  ["fd-002", "Full Synthetic Motor Oil 0W-20, 5 Quart", "Valvoline", "881160", "Fluids", "Motor Oil", "engine-oil", 29.75, 38.5, "summit", 210, 4.7, 1880, "N/A", "",
    "Low-viscosity full synthetic formulated for modern turbocharged and direct-injection engines.",
    [["Viscosity", "0W-20"], ["Volume", "5 qt"], ["Type", "Full synthetic"], ["Spec", "API SP / ILSAC GF-6A"]], CARS],
  ["fd-010", "Extended Life Antifreeze Coolant, 1 Gallon", "Prestone", "AF2100", "Fluids", "Antifreeze", "coolant", 22.5, 29.99, "keystone", 140, 4.5, 720, "N/A", "",
    "Pre-diluted 50/50 extended-life coolant compatible with all makes, protects to -34 F.",
    [["Concentration", "50/50 prediluted"], ["Volume", "1 gal"], ["Technology", "OAT"], ["Freeze Point", "-34 F"]], ALL],

  // ---------------- Body & Lighting ----------------
  ["bl-001", "Ultra White Halogen Headlight Bulb, H11", "Sylvania", "H11SU-BP2", "Body & Lighting", "Headlight Bulb", "headlight", 34.99, 44.99, "interstate", 55, 4.4, 512, "1 Year Limited", "",
    "Halogen capsule that puts out a whiter, farther-reaching beam than a standard bulb while staying street legal.",
    [["Base", "H11"], ["Wattage", "55W"], ["Voltage", "12V"], ["Quantity", "2"], ["Color Temp", "4100K"]], ALL],
  ["bl-002", "LED Headlight Conversion Kit, 9005", "Philips", "9005ULWX2", "Body & Lighting", "Headlight Bulb", "headlight", 89.95, 119.0, "apex", 16, 4.6, 388, "3 Year Limited", "",
    "Plug-and-play LED kit with an integrated driver and a beam pattern matched to a halogen reflector housing.",
    [["Base", "9005"], ["Wattage", "24W"], ["Voltage", "12V"], ["Quantity", "2"], ["Color Temp", "6000K"]], ALL],
  ["bl-010", "Beam Wiper Blade, 22 in", "Bosch", "22CA", "Body & Lighting", "Wiper Blade", "wiper", 24.99, 32.99, "midtown", 120, 4.5, 940, "1 Year Limited", "Driver",
    "Bracketless beam blade with a tensioned steel spine that keeps even pressure across the whole glass.",
    [["Length", "22 in"], ["Type", "Beam"], ["Connector", "Hook, J-style"], ["Quantity", "1"]], ALL],
  ["bl-011", "Beam Wiper Blade, 20 in", "Rain-X", "810164", "Body & Lighting", "Wiper Blade", "wiper", 18.4, 24.99, "northstar", 96, 4.3, 620, "1 Year Limited", "Passenger",
    "Water-repellent treated beam blade that transfers a hydrophobic coating to the windshield as it wipes.",
    [["Length", "20 in"], ["Type", "Beam"], ["Connector", "Multi-adapter"], ["Quantity", "1"]], ALL],
  ["bl-020", "Power Side View Mirror", "Dorman", "955-1667", "Body & Lighting", "Side Mirror", "mirror", 112.0, 148.0, "pacific", 6, 4.2, 71, "1 Year Limited", "Left",
    "Direct-fit powered mirror assembly with heat and turn signal, painted-ready housing and OE connector.",
    [["Side", "Left"], ["Power", "Yes"], ["Heated", "Yes"], ["Turn Signal", "Yes"], ["Finish", "Paint to match"]], TRUCKS],

  // ---------------- Fuel ----------------
  ["fu-001", "Electric Fuel Pump Module Assembly", "Delphi", "FG1489", "Fuel", "Fuel Pump", "fuel-pump", 214.5, 279.0, "gateway", 5, 4.5, 143, "2 Year Limited", "",
    "Complete in-tank module with pump, sending unit, strainer and reservoir, calibrated to OE pressure and flow.",
    [["Pressure", "58 psi"], ["Sending Unit", "Included"], ["Strainer", "Included"], ["Core Required", "No"]], ALL],

  // ======================================================================
  //  Fleet parts
  //
  //  Everything below is sized for the six commercial units in
  //  lib/suppliers.ts rather than for a retail driver. The id band names the
  //  unit the row was stocked for: x00 VAN-17, x10 VAN-22, x20 TRUCK-08,
  //  x30 TRUCK-12, x40 BOX-03, x50 BOX-07. Fitment stays deliberately narrow —
  //  a 235/65R16C van tire and a 19.5 in medium-duty tire share a category and
  //  nothing else — so a dispatcher searching on the unit's vehicle sees only
  //  what will actually bolt on.
  // ======================================================================

  // ------- VAN-17 · 2021 Ford Transit 250 · tire blowout -------
  ["wt-100", "Agilis CrossClimate Commercial Tire 235/65R16C", "Michelin", "05125", "Wheels & Tires", "Tire", "tire", 218.5, 264.0, "gateway", 26, 4.7, 512, "50,000 Mile Treadwear", "",
    "All-season commercial van tire with a reinforced casing and a tread designed to hold its shape under a fully loaded cargo box.",
    [["Size", "235/65R16C"], ["Load Index", "121/119"], ["Speed Rating", "R"], ["Ply Rating", "10"], ["Season", "All-season"]], [TRANSIT]],
  ["wt-101", "VanContact A/S Commercial Tire 235/65R16C", "Continental", "04515160000", "Wheels & Tires", "Tire", "tire", 189.99, 229.0, "interstate", 34, 4.5, 288, "50,000 Mile Treadwear", "",
    "High-load van tire with stiff shoulder blocks that resist the curbing and scrubbing of stop-and-go delivery routes.",
    [["Size", "235/65R16C"], ["Load Index", "121/119"], ["Speed Rating", "R"], ["Ply Rating", "10"], ["Season", "All-season"]], [TRANSIT]],
  ["wt-102", "16 in Steel Service Wheel", "Dorman", "939-320", "Wheels & Tires", "Wheel", "wheel", 132.0, 172.0, "pacific", 14, 4.2, 96, "1 Year Limited", "",
    "Black-painted steel wheel stamped to the original load rating, the usual replacement when a blowout takes the rim with it.",
    [["Diameter", "16 in"], ["Width", "6.5 in"], ["Bolt Pattern", "5 x 160mm"], ["Offset", "60mm"], ["Finish", "Black"]], [TRANSIT]],
  ["wt-103", "Programmable TPMS Sensor, 315 MHz", "Autel", "1-SENSOR-315", "Wheels & Tires", "TPMS Sensor", "tpms", 42.5, 58.0, "midtown", 88, 4.6, 430, "2 Year Limited", "",
    "Programmable sensor that clones the failed sensor's id, so a roadside tire swap does not leave the dash light on.",
    [["Frequency", "315 MHz"], ["Valve", "Rubber snap-in"], ["Battery Life", "Up to 7 years"], ["Programmable", "Yes"]], [TRANSIT, SPRINTER, F150F, SILVERADO_HD, E450]],
  ["wt-104", "Wheel Stud and Lug Nut Kit, M14 x 1.5", "Dorman", "611-207", "Wheels & Tires", "Lug Nuts", "lug-nut", 28.75, 38.5, "summit", 140, 4.4, 210, "1 Year Limited", "",
    "Ten hardened studs and cone-seat nuts, the parts most often stretched or galled when a wheel is changed on the shoulder.",
    [["Thread", "M14 x 1.5"], ["Seat", "Cone"], ["Pieces", "20"], ["Finish", "Zinc"]], FLEET_VANS],
  ["bp-100", "Coated Disc Brake Rotor, Front", "Bosch", "26011515", "Brakes", "Disc Brake Rotor", "brake-rotor", 78.4, 102.0, "northstar", 18, 4.5, 164, "2 Year Limited", "Front",
    "Fully coated van rotor with the vane count the loaded front axle needs to shed heat on repeated low-speed stops.",
    [["Outside Diameter", "12.99 in"], ["Thickness", "1.18 in"], ["Bolt Holes", "5"], ["Finish", "Coated"], ["Vented", "Yes"]], [TRANSIT]],
  ["bp-101", "Fleet Ceramic Brake Pad Set, Front", "Akebono", "ACT1846", "Brakes", "Brake Pad Set", "brake-pad", 62.9, 84.0, "keystone", 24, 4.6, 208, "3 Year Limited", "Front",
    "Ceramic pads rated for the duty cycle of a delivery route, with low dust so wheels stay clean between washes.",
    [["Friction", "Ceramic"], ["Shims", "Multi-layer"], ["Hardware", "Included"], ["Pieces", "4"]], [TRANSIT]],
  ["fl-100", "Full Synthetic Spin-On Oil Filter", "Motorcraft", "FL-500S", "Filters", "Oil Filter", "oil-filter", 12.4, 16.99, "midtown", 190, 4.7, 1420, "10,000 Miles", "",
    "OE Ford filter with a silicone anti-drainback valve, the filter both the Transit 3.5L and the F-150 fleet 3.3L take.",
    [["Height", "3.7 in"], ["Thread", "22mm x 1.5"], ["Anti-Drainback", "Silicone"], ["Bypass PSI", "12"]], [TRANSIT, F150F]],
  ["fl-101", "Panel Engine Air Filter", "Wix", "49146", "Filters", "Air Filter", "air-filter", 26.9, 35.5, "summit", 58, 4.5, 176, "1 Year Limited", "",
    "High-capacity pleated panel filter sized for the Transit airbox, with a polyurethane frame that seals against dust ingestion.",
    [["Type", "Cellulose panel"], ["Length", "13.2 in"], ["Width", "9.1 in"], ["Height", "2.0 in"]], [TRANSIT]],
  ["fl-102", "Carbon Cabin Air Filter", "Fram", "CF12094", "Filters", "Cabin Air Filter", "cabin-filter", 21.5, 28.99, "interstate", 72, 4.4, 148, "1 Year Limited", "",
    "Activated carbon cabin filter that keeps diesel and traffic fumes out of the cab on urban routes.",
    [["Media", "Carbon + particulate"], ["Length", "9.8 in"], ["Width", "8.1 in"], ["Height", "0.8 in"]], [TRANSIT]],
  ["en-100", "Platinum Spark Plug", "Motorcraft", "SP-534", "Engine", "Spark Plug", "spark-plug", 8.95, 12.5, "midtown", 180, 4.6, 640, "1 Year Limited", "",
    "OE plug for the 3.5L Ti-VCT, pre-gapped so a six-plug service does not need a gauge in the bay.",
    [["Electrode", "Platinum"], ["Gap", "0.043 in"], ["Thread", "14mm"], ["Reach", "0.749 in"], ["Heat Range", "5"]], [TRANSIT]],
  ["el-100", "AGM Automotive Battery, Group 48 (H6)", "ACDelco", "48AGM", "Electrical", "Battery", "battery", 249.0, 299.0, "gateway", 14, 4.6, 388, "3 Year Free Replacement", "",
    "Absorbed glass mat battery built for start-stop duty and the accessory load a delivery van carries with the engine off.",
    [["Group Size", "48 (H6)"], ["CCA", "760"], ["Reserve Capacity", "120 min"], ["Type", "AGM"], ["Terminal", "Top post"]], [TRANSIT, F150F]],
  ["su-100", "Wheel Bearing and Hub Assembly, Rear", "Timken", "HA590810", "Suspension & Steering", "Wheel Hub Assembly", "wheel-bearing", 158.5, 205.0, "summit", 11, 4.6, 142, "3 Year Limited", "Rear",
    "Sealed rear hub with a pre-set bearing preload and an integrated ABS ring, the assembly a blowout at speed usually takes out.",
    [["Bolt Pattern", "5 x 160mm"], ["ABS Sensor", "Integrated"], ["Studs", "Included"], ["Position", "Rear"]], [TRANSIT]],
  ["su-101", "Rear Leaf Spring Assembly, 5-Leaf", "Dorman", "929-802", "Suspension & Steering", "Leaf Spring", "leaf-spring", 268.0, 349.0, "apex", 4, 4.3, 74, "1 Year Limited", "Rear",
    "Five-leaf pack with new bushings and centre bolt, restoring ride height on a van that has been loaded to its rating daily.",
    [["Leaves", "5"], ["Bushings", "Included"], ["Centre Bolt", "Included"], ["Position", "Rear"]], [TRANSIT]],
  ["co-100", "Engine Cooling Fan Assembly", "Dorman", "621-535", "Cooling", "Radiator Fan", "radiator-fan", 218.0, 282.0, "pacific", 5, 4.3, 68, "1 Year Limited", "",
    "Complete fan, motor and shroud matched to OE airflow so the van holds temperature idling in a loading bay.",
    [["Blades", "9"], ["Motor", "Included"], ["Shroud", "Included"], ["Connector", "3-pin"]], [TRANSIT]],
  ["bl-100", "Beam Wiper Blade, 26 in", "Bosch", "26CA", "Body & Lighting", "Wiper Blade", "wiper", 27.5, 35.99, "northstar", 84, 4.5, 396, "1 Year Limited", "Driver",
    "Bracketless beam blade sized for the tall van windshield, with even pressure across the full sweep.",
    [["Length", "26 in"], ["Type", "Beam"], ["Connector", "Hook, J-style"], ["Quantity", "1"]], FLEET_VANS],

  // ------- VAN-22 · 2020 Mercedes-Benz Sprinter 2500 · alternator failure -------
  ["el-110", "Remanufactured Alternator, 250A", "Bosch", "AL0864X", "Electrical", "Alternator", "alternator", 386.0, 479.0, "apex", 5, 4.5, 132, "2 Year Limited", "",
    "Remanufactured high-output unit with new bearings, brushes, rectifier and regulator, load tested to full rated amperage before it ships.",
    [["Amperage", "250A"], ["Voltage", "12V"], ["Pulley", "Clutch, 6-groove"], ["Core Required", "Yes"]], [SPRINTER], 85],
  ["el-111", "New Alternator, 220A", "Valeo", "440640", "Electrical", "Alternator", "alternator", 512.0, 645.0, "summit", 3, 4.7, 78, "3 Year Limited", "",
    "Brand-new OE-supplier alternator with no core to return, the faster option when the van has to be back on route the same day.",
    [["Amperage", "220A"], ["Voltage", "12V"], ["Pulley", "Clutch, 6-groove"], ["Core Required", "No"]], [SPRINTER]],
  ["el-112", "AGM Automotive Battery, Group H8 (49)", "Bosch", "49-AGM", "Electrical", "Battery", "battery", 296.0, 359.0, "gateway", 8, 4.6, 264, "4 Year Free Replacement", "",
    "AGM starting battery for the diesel's glow and crank load; replace it with the alternator, because a failed charging system usually cooks the battery too.",
    [["Group Size", "H8 (49)"], ["CCA", "900"], ["Reserve Capacity", "160 min"], ["Type", "AGM"], ["Terminal", "Top post"]], [SPRINTER]],
  ["el-113", "Positive Battery Cable Assembly", "Dorman", "645-518", "Electrical", "Battery Cable", "battery-cable", 74.5, 98.0, "keystone", 16, 4.2, 86, "1 Year Limited", "",
    "Moulded positive cable with the OE terminal and fusible link, the part that hides a charging fault when its crimp corrodes.",
    [["Gauge", "2 AWG"], ["Length", "42 in"], ["Terminal", "OE clamp"], ["Fusible Link", "Included"]], FLEET_VANS],
  ["el-114", "Voltage Regulator with Brush Holder", "Bosch", "F00M145331", "Electrical", "Voltage Regulator", "alternator", 68.9, 92.0, "midtown", 22, 4.4, 118, "1 Year Limited", "",
    "Regulator and brush pack sold separately from the alternator, the cheap repair when the unit charges erratically but still spins true.",
    [["Voltage", "14.4V"], ["Brushes", "Included"], ["Fitment", "Bosch 250A"], ["Terminals", "3"]], [SPRINTER]],
  ["el-115", "Remanufactured Starter Motor", "Bosch", "SR0810X", "Electrical", "Starter Motor", "starter", 268.0, 342.0, "interstate", 6, 4.5, 94, "2 Year Limited", "",
    "Rebuilt diesel starter with a new solenoid and drive, bench tested for cranking speed and draw at the current a cold diesel actually pulls.",
    [["Teeth", "12"], ["Rotation", "Clockwise"], ["kW", "2.2"], ["Core Required", "Yes"]], [SPRINTER], 70],
  ["en-110", "Micro-V Serpentine Belt, 6-Rib", "Continental", "6PK1873", "Engine", "Serpentine Belt", "belt", 38.9, 52.0, "interstate", 42, 4.6, 188, "2 Year Limited", "",
    "EPDM belt cut to the diesel's accessory routing; a glazed or shredded belt is the other thing that stops an alternator charging.",
    [["Ribs", "6"], ["Length", "73.7 in"], ["Width", "0.84 in"], ["Material", "EPDM"]], [SPRINTER]],
  ["en-111", "Serpentine Belt Tensioner Assembly", "INA", "534029310", "Engine", "Belt Tensioner", "belt-tensioner", 96.4, 128.0, "northstar", 12, 4.5, 104, "2 Year Limited", "",
    "Complete tensioner with pulley and damper, replaced with the belt so the new belt is not asked to run on a worn spring.",
    [["Pulley", "Included"], ["Pulley Diameter", "70mm"], ["Damping", "Hydraulic"], ["Bolt", "Included"]], [SPRINTER]],
  ["en-112", "Glow Plug Set, 4 Piece", "Beru", "GN857", "Engine", "Glow Plug", "glow-plug", 82.0, 108.0, "apex", 20, 4.6, 156, "1 Year Limited", "",
    "Ceramic-tipped glow plugs matched as a set, so the diesel starts clean on a cold morning without the crank load that kills a weak battery.",
    [["Voltage", "11V"], ["Thread", "M10 x 1.0"], ["Pieces", "4"], ["Tip", "Ceramic"]], [SPRINTER]],
  ["fl-110", "Diesel Fuel Filter Service Kit", "Mann-Filter", "PU10021Z", "Filters", "Fuel Filter", "fuel-filter", 46.75, 62.0, "midtown", 36, 4.7, 240, "1 Year Limited", "",
    "Filter element with new seals and a water-separator bowl gasket, the scheduled service that keeps injector pressure where it belongs.",
    [["Type", "Element with seals"], ["Height", "5.3 in"], ["Water Separator", "Yes"], ["Seals", "Included"]], [SPRINTER]],
  ["fl-111", "Metal-Free Oil Filter Element", "Mann-Filter", "HU7008Z", "Filters", "Oil Filter", "oil-filter", 18.9, 26.0, "summit", 64, 4.8, 402, "1 Year Limited", "",
    "Ashless cartridge element that burns clean at disposal, specified for the low-SAPS oil this diesel and its particulate filter require.",
    [["Type", "Cartridge element"], ["Height", "4.4 in"], ["Outer Diameter", "2.8 in"], ["Seals", "Included"]], [SPRINTER]],
  ["fl-112", "Panel Engine Air Filter", "Mann-Filter", "C30005", "Filters", "Air Filter", "air-filter", 32.4, 42.5, "keystone", 40, 4.6, 132, "1 Year Limited", "",
    "OE-supplier panel filter with a stiff frame that will not distort in the Sprinter airbox and let unfiltered air past.",
    [["Type", "Cellulose panel"], ["Length", "11.4 in"], ["Width", "9.3 in"], ["Height", "2.3 in"]], [SPRINTER]],
  ["fl-113", "Charcoal Cabin Air Filter", "Corteco", "49356123", "Filters", "Cabin Air Filter", "cabin-filter", 28.5, 37.0, "pacific", 46, 4.4, 98, "1 Year Limited", "",
    "Activated charcoal cabin filter that pulls exhaust odour out of the cab while the van idles in traffic.",
    [["Media", "Carbon + particulate"], ["Length", "11.0 in"], ["Width", "8.6 in"], ["Height", "1.2 in"]], [SPRINTER]],
  ["fd-110", "Diesel Exhaust Fluid, 2.5 Gallon", "BlueDEF", "DEF002", "Fluids", "Diesel Exhaust Fluid", "def", 24.99, 32.0, "gateway", 165, 4.5, 860, "N/A", "",
    "API-certified 32.5% urea solution with an integrated spout; running the tank dry derates the engine and puts the van on the hook.",
    [["Concentration", "32.5% urea"], ["Volume", "2.5 gal"], ["Standard", "ISO 22241"], ["Spout", "Included"]], [SPRINTER]],
  ["fd-111", "Full Synthetic Diesel Engine Oil 5W-30, 5 Quart", "Mobil 1", "112798", "Fluids", "Motor Oil", "engine-oil", 44.5, 56.0, "summit", 96, 4.8, 1140, "N/A", "",
    "Low-SAPS full synthetic that meets the Mercedes-Benz 229.52 approval this engine and its particulate filter need.",
    [["Viscosity", "5W-30"], ["Volume", "5 qt"], ["Type", "Full synthetic"], ["Spec", "MB 229.52 / ACEA C3"]], [SPRINTER]],
  ["wt-110", "Transforce HT2 Commercial Tire 245/75R16E", "Firestone", "005730", "Wheels & Tires", "Tire", "tire", 232.0, 279.0, "gateway", 22, 4.6, 344, "50,000 Mile Treadwear", "",
    "Load range E commercial tire with a heavy casing and a highway tread that stays quiet at the weight a 2500 van carries.",
    [["Size", "245/75R16E"], ["Load Index", "120/116"], ["Speed Rating", "S"], ["Ply Rating", "10"], ["Season", "All-season"]], [SPRINTER]],
  ["bp-110", "Coated Disc Brake Rotor, Front", "Zimmermann", "400365420", "Brakes", "Disc Brake Rotor", "brake-rotor", 118.5, 152.0, "keystone", 12, 4.6, 118, "2 Year Limited", "Front",
    "Coated van rotor machined to the tight runout the Sprinter's floating caliper needs to avoid pedal pulsation.",
    [["Outside Diameter", "15.35 in"], ["Thickness", "1.42 in"], ["Bolt Holes", "6"], ["Finish", "Coated"], ["Vented", "Yes"]], [SPRINTER]],
  ["bp-111", "Low-Dust Brake Pad Set, Front", "Textar", "2508601", "Brakes", "Brake Pad Set", "brake-pad", 96.0, 126.0, "northstar", 16, 4.7, 186, "2 Year Limited", "Front",
    "OE-supplier pad set with wear sensors in the box, so the dash warning works after the job instead of staying lit.",
    [["Friction", "Low-metallic"], ["Wear Sensors", "Included"], ["Hardware", "Included"], ["Pieces", "4"]], [SPRINTER]],
  ["su-110", "Front Shock Absorber", "Sachs", "317572", "Suspension & Steering", "Shock Absorber", "shock", 98.5, 128.0, "apex", 10, 4.5, 92, "2 Year Limited", "Front",
    "OE-supplier twin-tube damper valved for a loaded van, keeping the front axle planted when the cargo box is full.",
    [["Type", "Twin-tube gas"], ["Extended Length", "21.9 in"], ["Compressed Length", "13.4 in"], ["Mount", "Pin/Eye"]], [SPRINTER]],

  // ------- TRUCK-08 · 2022 Ford F-150 XL Fleet · bent wheel after accident -------
  ["wt-120", "17 in Steel Fleet Wheel", "Dorman", "939-108", "Wheels & Tires", "Wheel", "wheel", 118.0, 154.0, "pacific", 16, 4.3, 108, "1 Year Limited", "",
    "Argent-painted steel wheel to the factory load rating and offset, the economical replacement for a rim bent in a collision.",
    [["Diameter", "17 in"], ["Width", "7.5 in"], ["Bolt Pattern", "6 x 135mm"], ["Offset", "44mm"], ["Finish", "Argent"]], [F150F]],
  ["wt-121", "17 in Machined Alloy Wheel", "Dorman", "939-142", "Wheels & Tires", "Wheel", "wheel", 214.0, 278.0, "apex", 7, 4.2, 64, "1 Year Limited", "",
    "OE-style machined alloy wheel, hub-centric and balanced, for a truck that has to match the other three corners.",
    [["Diameter", "17 in"], ["Width", "7.5 in"], ["Bolt Pattern", "6 x 135mm"], ["Offset", "44mm"], ["Finish", "Machined"]], [F150F]],
  ["wt-122", "All-Terrain T/A KO2 Tire 265/70R17", "BFGoodrich", "45771", "Wheels & Tires", "Tire", "tire", 246.99, 292.0, "gateway", 18, 4.8, 1260, "50,000 Mile Treadwear", "",
    "Light truck all-terrain with a reinforced sidewall, the usual pairing when a bent rim also destroyed the tire on it.",
    [["Size", "265/70R17"], ["Load Index", "121/118"], ["Speed Rating", "S"], ["Ply Rating", "10"], ["Season", "All-terrain"]], [F150F]],
  ["wt-123", "Wheel Stud and Lug Nut Set, 24 Piece", "Dorman", "610-561", "Wheels & Tires", "Lug Nuts", "lug-nut", 46.5, 62.0, "midtown", 90, 4.5, 254, "1 Year Limited", "",
    "Full set of hardened studs and nuts for a six-lug hub, because an impact hard enough to bend a wheel stretches the studs behind it.",
    [["Thread", "M14 x 1.5"], ["Seat", "Cone"], ["Pieces", "24"], ["Finish", "Zinc"]], [F150F, SILVERADO_HD, E450]],
  ["su-120", "Wheel Bearing and Hub Assembly, Front", "Timken", "HA590662", "Suspension & Steering", "Wheel Hub Assembly", "wheel-bearing", 168.5, 219.0, "summit", 12, 4.7, 232, "3 Year Limited", "Front",
    "Sealed front hub with integrated ABS ring, inspected as a matter of course after a wheel-first impact.",
    [["Bolt Pattern", "6 x 135mm"], ["ABS Sensor", "Integrated"], ["Studs", "Included"], ["Position", "Front"]], [F150F]],
  ["su-121", "Front Lower Control Arm with Ball Joint, Left", "Moog", "RK623456", "Suspension & Steering", "Control Arm", "control-arm", 152.0, 198.0, "apex", 9, 4.6, 148, "Limited Lifetime", "Front Lower Left",
    "Stamped-steel arm with a pressed-in greaseable ball joint and new bushings, the assembly that bends before the frame does.",
    [["Position", "Front lower left"], ["Ball Joint", "Included, greaseable"], ["Bushings", "Pressed in"], ["Material", "Stamped steel"]], [F150F]],
  ["su-122", "Problem Solver Outer Tie Rod End", "Moog", "ES801271", "Suspension & Steering", "Tie Rod End", "tie-rod", 42.9, 58.0, "midtown", 30, 4.7, 286, "Limited Lifetime", "Front Outer",
    "Hardened stud with a grease fitting, replaced in pairs when a wheel strike has pushed the toe out of spec.",
    [["Position", "Front outer"], ["Greaseable", "Yes"], ["Thread", "M14 x 1.5"], ["Stud Taper", "Standard"]], [F150F]],
  ["su-123", "Alignment Camber and Caster Bolt Kit", "Moog", "K100032", "Suspension & Steering", "Alignment Kit", "tie-rod", 34.5, 46.0, "keystone", 48, 4.4, 122, "1 Year Limited", "Front",
    "Eccentric bolt kit that buys back the camber and caster range an alignment rack needs after collision repair.",
    [["Adjustment", "±1.75 deg"], ["Bolt Size", "14mm"], ["Pieces", "2"], ["Position", "Front"]], [F150F]],
  ["su-124", "Front Shock Absorber", "Bilstein", "24-186384", "Suspension & Steering", "Shock Absorber", "shock", 108.0, 142.0, "northstar", 14, 4.7, 318, "Limited Lifetime", "Front",
    "Monotube gas damper that holds its valving under heat, worth fitting in pairs when one side has been through an impact.",
    [["Type", "Monotube gas"], ["Extended Length", "22.4 in"], ["Compressed Length", "14.1 in"], ["Mount", "Stem/Eye"]], [F150F]],
  ["bp-120", "Coated Disc Brake Rotor, Front", "Raybestos", "982246R", "Brakes", "Disc Brake Rotor", "brake-rotor", 84.5, 112.0, "interstate", 20, 4.5, 176, "2 Year Limited", "Front",
    "Coated front rotor to OE thickness and runout, commonly replaced with a bent wheel because the impact loads the hub face.",
    [["Outside Diameter", "13.78 in"], ["Thickness", "1.34 in"], ["Bolt Holes", "6"], ["Finish", "Coated"], ["Vented", "Yes"]], [F150F]],
  ["bp-121", "Severe Duty Semi-Metallic Brake Pad Set, Front", "Wagner", "MX1602", "Brakes", "Brake Pad Set", "brake-pad", 58.9, 78.0, "midtown", 32, 4.4, 214, "2 Year Limited", "Front",
    "Semi-metallic pads with a high-temperature binder for a truck that tows and carries service equipment every day.",
    [["Friction", "Semi-metallic"], ["Shims", "Steel"], ["Hardware", "Included"], ["Pieces", "4"]], [F150F]],
  ["bl-120", "Front Fender, Right", "Replace", "FO1241304", "Body & Lighting", "Fender", "fender", 268.0, 348.0, "pacific", 4, 4.1, 58, "1 Year Limited", "Right",
    "Stamped steel fender in primer, ready for paint, with the factory mounting holes and marker-lamp cut-out already in place.",
    [["Material", "Steel"], ["Finish", "Primed"], ["Side", "Right"], ["Marker Hole", "Yes"]], [F150F]],
  ["bl-121", "Halogen Headlight Assembly, Right", "TYC", "20-9945-00", "Body & Lighting", "Headlight Assembly", "headlight", 198.0, 262.0, "gateway", 6, 4.3, 142, "1 Year Limited", "Right",
    "Complete DOT-compliant housing with bulbs and adjusters, the assembly that cracks first in a front-corner impact.",
    [["Type", "Halogen reflector"], ["Bulbs", "Included"], ["Side", "Right"], ["Certification", "DOT/SAE"]], [F150F]],
  ["bl-122", "Power Heated Tow Mirror, Left", "Dorman", "955-1892", "Body & Lighting", "Side Mirror", "mirror", 232.0, 298.0, "apex", 5, 4.2, 88, "1 Year Limited", "Left",
    "Direct-fit powered tow mirror with heat and turn signal, the other casualty of a side impact on a work truck.",
    [["Side", "Left"], ["Power", "Yes"], ["Heated", "Yes"], ["Turn Signal", "Yes"], ["Finish", "Textured black"]], FLEET_PICKUPS],
  ["el-120", "ABS Wheel Speed Sensor, Front Left", "Standard", "ALS2892", "Electrical", "ABS Sensor", "abs-sensor", 58.4, 78.0, "apex", 24, 4.4, 162, "1 Year Limited", "Front Left",
    "Direct-fit speed sensor with the OE connector and lead length; its tone-ring gap is the first thing a wheel impact upsets.",
    [["Position", "Front left"], ["Connector", "2-pin OE"], ["Lead Length", "22 in"], ["Type", "Active"]], FLEET_PICKUPS],
  ["el-121", "Remanufactured Starter Motor", "Motorcraft", "SA-1010-RM", "Electrical", "Starter Motor", "starter", 186.0, 242.0, "keystone", 8, 4.5, 118, "2 Year Limited", "",
    "OE remanufactured starter with a new solenoid and drive, tested at the draw a cold V6 actually pulls.",
    [["Teeth", "11"], ["Rotation", "Clockwise"], ["kW", "1.6"], ["Core Required", "Yes"]], [F150F], 45],
  ["en-120", "Platinum Spark Plug", "Motorcraft", "SP-580", "Engine", "Spark Plug", "spark-plug", 9.4, 13.0, "summit", 165, 4.6, 520, "1 Year Limited", "",
    "OE plug for the 3.3L Ti-VCT fleet engine, pre-gapped and with the correct reach for the aluminium head.",
    [["Electrode", "Platinum"], ["Gap", "0.044 in"], ["Thread", "14mm"], ["Reach", "0.749 in"], ["Heat Range", "5"]], [F150F]],
  ["fl-120", "Panel Engine Air Filter", "Motorcraft", "FA-1927", "Filters", "Air Filter", "air-filter", 28.9, 38.0, "interstate", 52, 4.5, 186, "1 Year Limited", "",
    "OE panel filter with a moulded seal that keeps job-site dust out of the mass air flow sensor downstream.",
    [["Type", "Cellulose panel"], ["Length", "12.6 in"], ["Width", "9.8 in"], ["Height", "1.9 in"]], [F150F]],
  ["fl-121", "Carbon Cabin Air Filter", "Motorcraft", "FP-83", "Filters", "Cabin Air Filter", "cabin-filter", 24.5, 32.0, "midtown", 58, 4.4, 134, "1 Year Limited", "",
    "Carbon cabin filter for a truck that spends its day parked next to running equipment.",
    [["Media", "Carbon + particulate"], ["Length", "9.4 in"], ["Width", "8.7 in"], ["Height", "1.0 in"]], [F150F]],

  // ------- TRUCK-12 · 2021 Chevrolet Silverado 2500HD · brake failure -------
  ["bp-130", "Severe Duty Disc Brake Rotor, Front", "Raybestos", "580952", "Brakes", "Disc Brake Rotor", "brake-rotor", 128.5, 168.0, "summit", 14, 4.6, 196, "2 Year Limited", "Front",
    "Heavy-duty front rotor with the vane count a three-quarter-ton truck needs to shed heat on a long grade with a load behind it.",
    [["Outside Diameter", "14.06 in"], ["Thickness", "1.54 in"], ["Bolt Holes", "8"], ["Finish", "Coated"], ["Vented", "Yes"]], [SILVERADO_HD]],
  ["bp-131", "Severe Duty Disc Brake Rotor, Rear", "ACDelco", "177-1153", "Brakes", "Disc Brake Rotor", "brake-rotor", 112.0, 148.0, "interstate", 12, 4.5, 148, "2 Year Limited", "Rear",
    "OE-specification rear rotor with the integral parking-brake drum machined to the same tolerance as the friction face.",
    [["Outside Diameter", "14.09 in"], ["Thickness", "1.34 in"], ["Bolt Holes", "8"], ["Finish", "Coated"], ["Vented", "Yes"]], [SILVERADO_HD]],
  ["bp-132", "Severe Duty Semi-Metallic Brake Pad Set, Front", "Wagner", "MX1093", "Brakes", "Brake Pad Set", "brake-pad", 74.5, 98.0, "northstar", 26, 4.5, 268, "2 Year Limited", "Front",
    "Semi-metallic friction rated for heavy tow duty, holding its coefficient at the temperature where a lighter pad fades away.",
    [["Friction", "Semi-metallic"], ["Shims", "Steel"], ["Hardware", "Included"], ["Pieces", "4"]], [SILVERADO_HD]],
  ["bp-133", "Fleet Ceramic Brake Pad Set, Rear", "Akebono", "ACT1092", "Brakes", "Brake Pad Set", "brake-pad", 68.9, 92.0, "keystone", 20, 4.7, 204, "3 Year Limited", "Rear",
    "Ceramic rear pads that hold a stable pedal without chewing the rotor, sized for the 8-lug rear caliper.",
    [["Friction", "Ceramic"], ["Shims", "Multi-layer"], ["Hardware", "Included"], ["Pieces", "4"]], [SILVERADO_HD]],
  ["bp-134", "Loaded Brake Caliper, Front Left", "Cardone", "18-B5482", "Brakes", "Brake Caliper", "brake-caliper", 168.0, 218.0, "apex", 6, 4.3, 96, "2 Year Limited", "Front Left",
    "Remanufactured caliper shipped loaded with pads and hardware, pressure tested; a seized piston is the usual cause of a one-sided brake failure.",
    [["Bore", "2.36 in"], ["Piston", "Steel"], ["Pads Included", "Yes"], ["Core Required", "Yes"]], [SILVERADO_HD], 65],
  ["bp-135", "Brake Hydraulic Hose, Front", "Dorman", "H621358", "Brakes", "Brake Hose", "brake-hose", 26.4, 34.99, "midtown", 44, 4.4, 178, "1 Year Limited", "Front",
    "DOT-compliant flexible hose with crimped fittings; an internally collapsed hose drags one brake and lets the other one fade.",
    [["Standard", "DOT SAE J1401"], ["Length", "18.5 in"], ["Fittings", "Banjo / inverted flare"], ["Hardware", "Included"]], FLEET_PICKUPS],
  ["bp-136", "Brake Master Cylinder", "Cardone", "10-4200", "Brakes", "Master Cylinder", "master-cylinder", 168.5, 218.0, "keystone", 7, 4.3, 108, "2 Year Limited", "",
    "Remanufactured master cylinder with new seals and a bench-bled reservoir, the part behind a pedal that sinks slowly to the floor.",
    [["Bore", "1.25 in"], ["Reservoir", "Included"], ["Ports", "2"], ["Bench Bled", "Yes"]], [SILVERADO_HD]],
  ["bp-137", "Brake Hardware and Shim Kit, Front", "Carlson", "H5813Q", "Brakes", "Brake Hardware Kit", "brake-pad", 18.9, 26.0, "northstar", 62, 4.5, 240, "1 Year Limited", "Front",
    "Abutment clips, slide pins, boots and grease, so the new pads can move in the bracket instead of binding it.",
    [["Clips", "Included"], ["Slide Pins", "Included"], ["Boots", "Included"], ["Grease", "Included"]], [SILVERADO_HD]],
  ["fd-130", "DOT 3 Brake Fluid, 32 oz", "Prestone", "AS401", "Fluids", "Brake Fluid", "brake-fluid", 9.99, 13.5, "midtown", 210, 4.6, 980, "N/A", "",
    "Sealed DOT 3 fluid for the flush that has to follow any hydraulic repair; moisture in old fluid is what boils a pedal away on a descent.",
    [["Standard", "DOT 3"], ["Volume", "32 oz"], ["Dry Boiling Point", "460 F"], ["Wet Boiling Point", "284 F"]], FLEET],
  ["fl-130", "Professional Engine Oil Filter", "ACDelco", "PF48", "Filters", "Oil Filter", "oil-filter", 13.9, 18.5, "summit", 120, 4.7, 640, "1 Year Limited", "",
    "OE-specification filter for the 6.6L V8 with a high-capacity element sized for the sump this engine carries.",
    [["Height", "5.2 in"], ["Thread", "M22 x 1.5"], ["Anti-Drainback", "Silicone"], ["Bypass PSI", "22"]], [SILVERADO_HD]],
  ["fl-131", "Rigid Panel Engine Air Filter", "ACDelco", "A3195C", "Filters", "Air Filter", "air-filter", 34.5, 45.0, "interstate", 44, 4.5, 168, "1 Year Limited", "",
    "High-capacity panel filter for the HD airbox, with a rigid frame that will not bow under the airflow this V8 pulls.",
    [["Type", "Cellulose panel"], ["Length", "14.2 in"], ["Width", "10.6 in"], ["Height", "2.2 in"]], [SILVERADO_HD]],
  ["en-130", "Iridium Spark Plug", "ACDelco", "41-114", "Engine", "Spark Plug", "spark-plug", 10.8, 14.5, "midtown", 148, 4.7, 486, "1 Year Limited", "",
    "OE iridium plug for the 6.6L L8T, pre-gapped for the coil energy this ignition system delivers.",
    [["Electrode", "Iridium"], ["Gap", "0.040 in"], ["Thread", "14mm"], ["Reach", "0.749 in"], ["Heat Range", "6"]], [SILVERADO_HD]],
  ["el-130", "Heavy Duty AGM Battery, Group 94R (H7)", "ACDelco", "94RAGM", "Electrical", "Battery", "battery", 289.0, 349.0, "gateway", 10, 4.6, 342, "4 Year Free Replacement", "",
    "AGM battery for a truck running a lift gate, inverter and beacon off the same electrical system.",
    [["Group Size", "94R (H7)"], ["CCA", "850"], ["Reserve Capacity", "140 min"], ["Type", "AGM"], ["Terminal", "Top post"]], [SILVERADO_HD]],
  ["el-131", "Remanufactured Alternator, 220A", "ACDelco", "334-2919", "Electrical", "Alternator", "alternator", 268.0, 342.0, "apex", 6, 4.4, 126, "2 Year Limited", "",
    "Remanufactured high-output alternator with a new regulator and rectifier, rated for the accessory load an HD work truck carries.",
    [["Amperage", "220A"], ["Voltage", "12V"], ["Pulley", "Clutch, 6-groove"], ["Core Required", "Yes"]], [SILVERADO_HD], 70],
  ["wt-130", "Transforce AT2 Light Truck Tire LT265/70R18E", "Firestone", "008460", "Wheels & Tires", "Tire", "tire", 268.0, 318.0, "gateway", 16, 4.6, 428, "50,000 Mile Treadwear", "",
    "Load range E all-terrain tire with a heavy casing, matched to the axle rating of a three-quarter-ton truck.",
    [["Size", "LT265/70R18E"], ["Load Index", "124/121"], ["Speed Rating", "S"], ["Ply Rating", "10"], ["Season", "All-terrain"]], [SILVERADO_HD]],
  ["su-130", "Heavy Duty Rear Shock Absorber", "Monroe", "911500", "Suspension & Steering", "Shock Absorber", "shock", 88.0, 116.0, "northstar", 18, 4.5, 204, "Limited Lifetime", "Rear",
    "Large-bore gas shock valved for a loaded leaf-sprung rear axle, so the tail stops pattering under braking.",
    [["Type", "Twin-tube gas"], ["Extended Length", "26.3 in"], ["Compressed Length", "16.1 in"], ["Mount", "Eye/Eye"]], [SILVERADO_HD, E450]],

  // ------- BOX-03 · 2019 Ford E-450 box truck · battery and cooling failure -------
  ["co-140", "Heavy Duty Radiator Assembly", "Spectra Premium", "CU2887", "Cooling", "Radiator", "radiator", 386.0, 495.0, "apex", 5, 4.4, 96, "2 Year Limited", "",
    "Two-row aluminium-core radiator with an integral transmission cooler, pressure tested and shipped with new mounting hardware.",
    [["Core Rows", "2"], ["Core Height", "20.9 in"], ["Core Width", "28.5 in"], ["Inlet", "1.75 in"], ["Trans Cooler", "Yes"]], [E450]],
  ["co-141", "Upper Radiator Hose", "Gates", "23036", "Cooling", "Radiator Hose", "radiator-hose", 32.5, 44.0, "midtown", 32, 4.5, 142, "1 Year Limited", "Upper",
    "Moulded EPDM hose with the OE bend radius, so it clears the fan shroud instead of chafing on it.",
    [["Position", "Upper"], ["Material", "EPDM"], ["Inside Diameter", "1.75 in"], ["Clamps", "Not included"]], [E450]],
  ["co-142", "Lower Radiator Hose", "Gates", "24003", "Cooling", "Radiator Hose", "radiator-hose", 36.9, 48.0, "interstate", 26, 4.5, 118, "1 Year Limited", "Lower",
    "Moulded lower hose with an internal wire coil that keeps it from collapsing under suction at high engine speed.",
    [["Position", "Lower"], ["Material", "EPDM"], ["Inside Diameter", "1.75 in"], ["Anti-Collapse Coil", "Yes"]], [E450]],
  ["co-143", "Coolant Recovery Reservoir", "Dorman", "603-244", "Cooling", "Coolant Reservoir", "coolant-tank", 68.0, 89.0, "summit", 10, 4.3, 88, "1 Year Limited", "",
    "Moulded degas bottle with the level marks and cap seat intact; a crazed original tank is a slow coolant loss nobody finds until it overheats.",
    [["Capacity", "2.1 qt"], ["Cap", "Not included"], ["Sensor Port", "Yes"], ["Material", "Moulded polymer"]], [E450]],
  ["co-144", "Thermal Fan Clutch", "Hayden", "2789", "Cooling", "Fan Clutch", "fan-clutch", 148.5, 195.0, "northstar", 7, 4.5, 132, "1 Year Limited", "",
    "Bimetal thermal clutch that locks up as the radiator outlet heats; a slipping clutch overheats a box truck at low speed and looks fine on the highway.",
    [["Type", "Thermal, heavy duty"], ["Rotation", "Clockwise"], ["Thread", "M32 x 1.5"], ["Engagement", "Bimetal coil"]], [E450]],
  ["co-145", "Engine Water Pump", "Gates", "43542", "Cooling", "Water Pump", "water-pump", 118.0, 152.0, "keystone", 9, 4.5, 148, "2 Year Limited", "",
    "Cast-iron housing pump with a heavy-duty bearing and mechanical seal, rated for the coolant flow the V10 needs at full load.",
    [["Impeller", "Cast iron"], ["Gasket", "Included"], ["Pulley", "Not included"], ["Inlet", "1.75 in"]], [E450]],
  ["co-146", "Engine Coolant Thermostat, 195 F", "Motorad", "7255-195", "Cooling", "Thermostat", "thermostat", 18.5, 25.0, "midtown", 54, 4.4, 116, "1 Year Limited", "",
    "Calibrated wax-pellet thermostat with a stainless frame, replaced with the pump so a stuck valve does not spoil the repair.",
    [["Opening Temp", "195 F"], ["Diameter", "54mm"], ["Housing", "Not included"], ["Gasket", "Included"]], [E450]],
  ["co-147", "Radiator Pressure Cap, 16 psi", "Stant", "10230", "Cooling", "Radiator Cap", "radiator", 12.4, 17.0, "summit", 96, 4.5, 226, "1 Year Limited", "",
    "Correct-rating cap with a new seal; a cap that no longer holds pressure lets the coolant boil well below its rated temperature.",
    [["Pressure Rating", "16 psi"], ["Type", "Lever-less"], ["Seal", "Nitrile"], ["Fitment", "Standard neck"]], [E450]],
  ["fd-140", "Orange Extended Life Coolant Concentrate, 1 Gallon", "Motorcraft", "VC-3-B", "Fluids", "Antifreeze", "coolant", 28.9, 37.5, "keystone", 120, 4.6, 540, "N/A", "",
    "Concentrated orange HOAT coolant specified for these Ford engines; mixing it with a green conventional coolant is what gels a cooling system.",
    [["Concentration", "Concentrate"], ["Volume", "1 gal"], ["Technology", "HOAT"], ["Colour", "Orange"]], FLEET_FORD],
  ["el-140", "Heavy Duty Commercial Battery, Group 65", "Motorcraft", "BXT-65-850", "Electrical", "Battery", "battery", 268.0, 329.0, "gateway", 11, 4.5, 246, "3 Year Free Replacement", "",
    "OE commercial battery with the reserve capacity a truck needs when its lift gate and beacons run long after the engine is off.",
    [["Group Size", "65"], ["CCA", "850"], ["Reserve Capacity", "150 min"], ["Type", "Flooded"], ["Terminal", "Top post"]], [E450]],
  ["el-141", "Dual Battery Cable Set", "Dorman", "645-533", "Electrical", "Battery Cable", "battery-cable", 96.5, 128.0, "apex", 12, 4.3, 74, "1 Year Limited", "",
    "Positive and negative cables with the auxiliary battery jumper, the harness that corrodes first on a truck parked outdoors year-round.",
    [["Gauge", "1/0 AWG"], ["Cables", "3"], ["Terminals", "OE clamp"], ["Length", "Positive 60 in"]], [E450]],
  ["el-142", "Remanufactured Alternator, 130A", "Motorcraft", "GL-950-RM", "Electrical", "Alternator", "alternator", 224.0, 289.0, "summit", 7, 4.4, 138, "2 Year Limited", "",
    "OE remanufactured 6G alternator with a new regulator and rectifier; a battery that keeps dying is usually this, not the battery.",
    [["Amperage", "130A"], ["Voltage", "12V"], ["Pulley", "6-groove"], ["Core Required", "Yes"]], [E450], 60],
  ["fl-140", "Spin-On Oil Filter", "Motorcraft", "FL-1A", "Filters", "Oil Filter", "oil-filter", 11.9, 16.0, "midtown", 168, 4.6, 820, "5,000 Miles", "",
    "Large-capacity OE filter for the 6.8L V10, with a steel base plate that will not distort at the pressure this engine runs cold.",
    [["Height", "5.2 in"], ["Thread", "3/4-16"], ["Anti-Drainback", "Silicone"], ["Bypass PSI", "15"]], [E450]],
  ["fl-141", "Heavy Duty Panel Air Filter", "Motorcraft", "FA-1785", "Filters", "Air Filter", "air-filter", 38.5, 49.0, "interstate", 38, 4.5, 164, "1 Year Limited", "",
    "Deep-pleat panel filter with the dust capacity a distribution truck needs between service intervals.",
    [["Type", "Cellulose panel"], ["Length", "13.9 in"], ["Width", "11.2 in"], ["Height", "2.4 in"]], [E450]],
  ["en-140", "Platinum Spark Plug", "Motorcraft", "SP-493", "Engine", "Spark Plug", "spark-plug", 9.75, 13.25, "summit", 210, 4.5, 468, "1 Year Limited", "",
    "OE plug for the 6.8L V10, with the tapered seat and reach this head takes; ten of them make a full set.",
    [["Electrode", "Platinum"], ["Gap", "0.042 in"], ["Thread", "16mm"], ["Reach", "0.750 in"], ["Heat Range", "5"]], [E450]],
  ["dr-140", "Driveshaft Universal Joint", "Spicer", "5-153X", "Drivetrain", "U-Joint", "u-joint", 42.5, 58.0, "summit", 26, 4.6, 186, "1 Year Limited", "",
    "Greaseable u-joint with a full-round bearing kit, the wear item behind the driveline vibration a loaded box truck develops.",
    [["Cap Diameter", "1.125 in"], ["Span", "3.219 in"], ["Greaseable", "Yes"], ["Snap Rings", "Included"]], FLEET_BOX],
  ["wt-140", "Transforce HT2 Commercial Tire 225/75R16E", "Firestone", "005720", "Wheels & Tires", "Tire", "tire", 214.0, 258.0, "gateway", 20, 4.5, 302, "50,000 Mile Treadwear", "",
    "Load range E steer tire with a rib tread that tracks straight under the front-axle weight of a cutaway box body.",
    [["Size", "225/75R16E"], ["Load Index", "115/112"], ["Speed Rating", "S"], ["Ply Rating", "10"], ["Season", "All-season"]], [E450]],
  ["bp-140", "Severe Duty Disc Brake Rotor, Front", "Raybestos", "56746R", "Brakes", "Disc Brake Rotor", "brake-rotor", 132.0, 172.0, "keystone", 10, 4.4, 124, "2 Year Limited", "Front",
    "Heavy-duty vented rotor for a cutaway chassis, machined to a runout tight enough to keep a loaded truck from pulsing under braking.",
    [["Outside Diameter", "13.03 in"], ["Thickness", "1.42 in"], ["Bolt Holes", "8"], ["Finish", "Bare"], ["Vented", "Yes"]], [E450]],
  ["bp-141", "Severe Duty Semi-Metallic Brake Pad Set, Front", "Wagner", "MX1071", "Brakes", "Brake Pad Set", "brake-pad", 72.0, 94.0, "northstar", 22, 4.4, 156, "2 Year Limited", "Front",
    "Semi-metallic pads with the thermal headroom a fully loaded box truck needs on a long descent.",
    [["Friction", "Semi-metallic"], ["Shims", "Steel"], ["Hardware", "Included"], ["Pieces", "4"]], [E450]],
  ["su-140", "Rear Leaf Spring Assembly, 7-Leaf Heavy Duty", "Dorman", "929-830", "Suspension & Steering", "Leaf Spring", "leaf-spring", 428.0, 549.0, "apex", 3, 4.2, 52, "1 Year Limited", "Rear",
    "Seven-leaf heavy-duty pack with new bushings, restoring the ride height and rating of a chassis that has been at its limit for years.",
    [["Leaves", "7"], ["Bushings", "Included"], ["Centre Bolt", "Included"], ["Position", "Rear"]], [E450]],

  // ------- BOX-07 · 2020 Isuzu NPR · tire and brake incident -------
  ["wt-150", "R268 Ecopia All-Position Tire 245/70R19.5", "Bridgestone", "004283", "Wheels & Tires", "Tire", "tire", 349.0, 419.0, "gateway", 14, 4.6, 268, "Casing Warranty, 5 Year", "",
    "Load range H all-position commercial tire with a low-rolling-resistance rib tread, the standard fit on a medium-duty cab-over.",
    [["Size", "245/70R19.5"], ["Load Index", "135/133"], ["Speed Rating", "J"], ["Ply Rating", "16"], ["Position", "All-position"]], [NPR]],
  ["wt-151", "19.5 in Steel Disc Wheel", "Accuride", "29408", "Wheels & Tires", "Wheel", "wheel", 218.0, 278.0, "pacific", 9, 4.4, 86, "1 Year Limited", "",
    "Hub-piloted steel disc wheel to the original load rating, the replacement when a kerb strike puts a flat spot in the rim.",
    [["Diameter", "19.5 in"], ["Width", "6.75 in"], ["Bolt Pattern", "6 x 222.25mm"], ["Offset", "142mm"], ["Finish", "White powder coat"]], [NPR]],
  ["wt-152", "Heavy Duty Wheel Nut Set, M22 x 1.5", "Dorman", "611-085", "Wheels & Tires", "Lug Nuts", "lug-nut", 68.5, 89.0, "summit", 54, 4.5, 118, "1 Year Limited", "",
    "Flange nuts for a hub-piloted medium-duty wheel, torqued in sequence; reusing stretched nuts is how a wheel comes loose twice.",
    [["Thread", "M22 x 1.5"], ["Seat", "Flange"], ["Pieces", "12"], ["Finish", "Zinc"]], [NPR]],
  ["bp-150", "Disc Brake Rotor, Front", "Fleetrite", "FLT21996", "Brakes", "Disc Brake Rotor", "brake-rotor", 178.0, 228.0, "summit", 8, 4.4, 92, "1 Year Limited", "Front",
    "Medium-duty front rotor machined to the OE thickness and runout the NPR's fixed caliper needs to wear evenly.",
    [["Outside Diameter", "12.99 in"], ["Thickness", "1.65 in"], ["Bolt Holes", "6"], ["Finish", "Bare"], ["Vented", "Yes"]], [NPR]],
  ["bp-151", "Disc Brake Rotor, Rear", "Fleetrite", "FLT21997", "Brakes", "Disc Brake Rotor", "brake-rotor", 152.0, 198.0, "interstate", 6, 4.3, 74, "1 Year Limited", "Rear",
    "Rear rotor for the cab-over chassis, replaced in pairs so the axle brakes evenly under a full body load.",
    [["Outside Diameter", "12.60 in"], ["Thickness", "1.42 in"], ["Bolt Holes", "6"], ["Finish", "Bare"], ["Vented", "Yes"]], [NPR]],
  ["bp-152", "Severe Duty Brake Pad Set, Front", "Fleetrite", "FLT4812", "Brakes", "Brake Pad Set", "brake-pad", 128.0, 168.0, "northstar", 16, 4.5, 108, "1 Year Limited", "Front",
    "Medium-duty friction with the thermal capacity for urban freight, where the brakes do the work a gearbox would on the highway.",
    [["Friction", "Semi-metallic"], ["Shims", "Steel"], ["Hardware", "Included"], ["Pieces", "4"]], [NPR]],
  ["bp-153", "Remanufactured Brake Caliper, Front Right", "Cardone", "19-B7284", "Brakes", "Brake Caliper", "brake-caliper", 268.0, 342.0, "apex", 3, 4.2, 58, "1 Year Limited", "Front Right",
    "Remanufactured medium-duty caliper with new seals, boots and hardware, pressure tested; a dragging caliper is what cooks a rotor blue.",
    [["Bore", "2.75 in"], ["Piston", "Steel"], ["Bracket", "Included"], ["Core Required", "Yes"]], [NPR], 95],
  ["su-150", "Front Wheel Seal and Bearing Kit", "Timken", "SET415", "Suspension & Steering", "Wheel Bearing Kit", "wheel-bearing", 148.5, 192.0, "keystone", 11, 4.6, 96, "1 Year Limited", "Front",
    "Matched cup, cone and seal set for the front hub, the parts that have to come out anyway once the wheel end has been opened.",
    [["Bearings", "Cup and cone, 2 sets"], ["Seal", "Included"], ["Position", "Front"], ["Serviceable", "Yes"]], [NPR]],
  ["fl-150", "Spin-On Oil Filter", "Wix", "51516", "Filters", "Oil Filter", "oil-filter", 14.5, 19.5, "midtown", 132, 4.6, 386, "5,000 Miles", "",
    "Heavy-duty spin-on filter with a wire-backed element, sized for the sump and service interval of a medium-duty gas V8.",
    [["Height", "5.1 in"], ["Thread", "3/4-16"], ["Anti-Drainback", "Silicone"], ["Bypass PSI", "13"]], [NPR]],
  ["fl-151", "Radial Seal Air Filter Element", "Wix", "46754", "Filters", "Air Filter", "air-filter", 62.0, 82.0, "summit", 28, 4.6, 142, "1 Year Limited", "",
    "Radial-seal cylindrical element for the cab-over air cleaner, with far more dust capacity than a panel filter.",
    [["Type", "Radial seal element"], ["Height", "10.4 in"], ["Outer Diameter", "6.9 in"], ["Seal", "Integral urethane"]], [NPR]],
  ["fl-152", "In-Line Fuel Filter", "Wix", "33481", "Filters", "Fuel Filter", "fuel-filter", 26.9, 35.5, "interstate", 48, 4.4, 118, "1 Year Limited", "",
    "Spin-on fuel filter with a water drain, the scheduled service that keeps a medium-duty fuel system off the side of the road.",
    [["Type", "Spin-on"], ["Height", "5.4 in"], ["Thread", "M20 x 1.5"], ["Water Drain", "Yes"]], [NPR]],
  ["el-150", "Commercial Battery, Group 31", "Odyssey", "31-PC2150S", "Electrical", "Battery", "battery", 398.0, 479.0, "gateway", 6, 4.7, 214, "4 Year Free Replacement", "",
    "Group 31 AGM battery with the cranking amps a medium-duty truck needs and the cycle life for a body with a power tail lift.",
    [["Group Size", "31"], ["CCA", "1150"], ["Reserve Capacity", "205 min"], ["Type", "AGM"], ["Terminal", "Stud"]], [NPR]],
  ["el-151", "Remanufactured Starter Motor", "Denso", "280-4256", "Electrical", "Starter Motor", "starter", 318.0, 402.0, "apex", 4, 4.5, 88, "2 Year Limited", "",
    "Rebuilt gear-reduction starter for the 6.0L, bench tested at the draw a medium-duty engine pulls on a cold morning.",
    [["Teeth", "11"], ["Rotation", "Clockwise"], ["kW", "2.5"], ["Core Required", "Yes"]], [NPR], 80],
  ["en-150", "Micro-V Serpentine Belt, 8-Rib", "Gates", "K081065", "Engine", "Serpentine Belt", "belt", 42.5, 56.0, "keystone", 34, 4.6, 148, "2 Year Limited", "",
    "Eight-rib EPDM belt for the medium-duty accessory drive, holding tension against a large alternator and an air-conditioning compressor.",
    [["Ribs", "8"], ["Length", "106.5 in"], ["Width", "1.09 in"], ["Material", "EPDM"]], [NPR]],
  ["bl-150", "Cab Wiper Blade, 22 in", "Trico", "61-220", "Body & Lighting", "Wiper Blade", "wiper", 19.9, 26.5, "midtown", 92, 4.3, 208, "1 Year Limited", "Driver",
    "Steel-frame commercial blade with a heavy spine, chosen for a flat cab-over windshield that a beam blade struggles to follow.",
    [["Length", "22 in"], ["Type", "Conventional frame"], ["Connector", "Hook, J-style"], ["Quantity", "1"]], FLEET_BOX],
  ["fd-150", "Fleet Full Synthetic Motor Oil 5W-30, 5 Gallon Pail", "Valvoline", "VV1085", "Fluids", "Motor Oil", "engine-oil", 168.0, 214.0, "summit", 34, 4.7, 262, "N/A", "",
    "Bulk pail for a shop doing its own oil changes across the fleet, at the API SP specification every unit here takes.",
    [["Viscosity", "5W-30"], ["Volume", "5 gal"], ["Type", "Full synthetic"], ["Spec", "API SP / ILSAC GF-6A"]], FLEET],
];

export const products: Product[] = rows.map((r) => ({
  id: r[0],
  name: r[1],
  brand: r[2],
  partNumber: r[3],
  category: r[4],
  subCategory: r[5],
  image: `/parts/${r[6]}.svg`,
  price: r[7],
  listPrice: r[8],
  supplierId: r[9],
  stock: r[10],
  rating: r[11],
  reviews: r[12],
  warranty: r[13],
  position: r[14] || undefined,
  description: r[15],
  specs: r[16].map(([label, value]) => ({ label, value })),
  fits: r[17],
  core: r[18],
}));

export const productById = Object.fromEntries(products.map((p) => [p.id, p]));

export const categories = Array.from(new Set(products.map((p) => p.category)));

export const subCategoriesByCategory = categories.map((c) => ({
  category: c,
  subCategories: Array.from(
    new Set(products.filter((p) => p.category === c).map((p) => p.subCategory))
  ),
}));

export const brands = Array.from(new Set(products.map((p) => p.brand))).sort();

export const money = (n: number) =>
  n.toLocaleString("en-US", { style: "currency", currency: "USD" });
